# Generated by Django 5.0.6 on 2024-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sabor', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidades', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
